import '@/app/globals.css'
import type { ReactNode } from 'react'
import { Work_Sans } from 'next/font/google'

const workSans = Work_Sans({
  weight: 'variable',
  subsets: ['latin'],
  display: 'auto',
  fallback: ['sans-serif'],
})

export const metadata = {
  title: 'Bizwizz',
  description: 'Generated by create next app',
  key: 'landing page',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={workSans.className}>{children}</body>
    </html>
  )
}
